/* Original playing interface, with Black 2 objectives and preparation. */
(function(root){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function createPlayingGuide(ctx){let host,tab='now';const p=ctx.getProgress;const link=(id,text)=>`<button type="button" data-playing-area="${esc(id)}">${esc(text||ctx.areas.find(a=>a[0]===id)?.[1]||id)} ↗</button>`;
 function now(){const state=p(),i=state.chapter||0,c=ctx.chapters[i],tasks=ctx.editorial.tasks[i];return `<section class="playing-objective"><small>${esc(c.when)}</small><h2>${esc(c.title)}</h2><p>${esc(state.spoilerFree?'Acompanhe as tarefas da etapa atual.':c.text)}</p>${tasks.map(t=>`<label class="playing-task"><input type="checkbox" data-playing-task="${t.id}" ${state.tasks.includes(t.id)?'checked':''}><span>${esc(t.text)}</span></label>`).join('')}<small>Estas tarefas não alteram suas insígnias. Atualize seu avanço em Minha jornada, no mapa.</small></section><section class="playing-place"><h2>Onde parei</h2><label for="playing-place">Local da partida</label><select id="playing-place"><option value="">Escolha um lugar</option>${ctx.areas.filter(a=>!ctx.spoilerLocked(a)).map(a=>`<option value="${a[0]}" ${state.playArea===a[0]?'selected':''}>${esc(a[1])}</option>`).join('')}</select>${state.playArea?link(state.playArea,'Abrir este local'):''}<label for="playing-note">Lembrete para continuar</label><textarea id="playing-note" rows="3" maxlength="1000" placeholder="Ex.: procurar o próximo integrante da equipe">${esc(state.playNote)}</textarea><small id="playing-save" role="status">Salvo automaticamente neste aparelho.</small></section>`;}
 function battle(b){return `<details class="battle-card"><summary><span><b>${esc(b.name)}</b><small>${b.team?b.team.map(r=>r[1]).reduce((a,b)=>Math.max(a,b),0)+' · nível do mais forte':''}</small></span><span aria-hidden="true">+</span></summary><div class="battle-content"><div class="battle-roster">${b.team.map(([n,l])=>`<div><b>${esc(n)}</b><small>Nv. ${l}</small></div>`).join('')}</div><h3>Preste atenção</h3><p>${esc(b.danger)}</p><h3>Como se preparar</h3><p>${esc(b.advice)}</p>${link(b.area)}<a href="${battleGuideData.sources[b.source]}" target="_blank" rel="noopener noreferrer">Conferir equipe e golpes ↗</a></div></details>`;}
 function battles(){const state=p();return `<p class="plan-footnote">Complete Unova v1.12. Os times alterados ainda precisam de confirmação; consulte as dicas de preparação e a ficha do local.</p><details class="battle-card"><summary><b>Antes de uma batalha importante</b><span aria-hidden="true">+</span></summary><div class="battle-content"><ul><li>Cure HP, condições de status e confira os PP.</li><li>Prepare cura e uma alternativa ao atacante principal.</li><li>Confira os golpes e as habilidades, além dos tipos.</li><li>Salve antes de começar.</li></ul></div></details>${Object.entries(black2Extra.battleTips).map(([name,text])=>`<details class="battle-card"><summary><b>${esc(name)}</b><span aria-hidden="true">+</span></summary><div class="battle-content"><p>${esc(text)}</p></div></details>`).join('')}<h2 class="playing-section-title">Capturas lendárias</h2><details class="battle-card"><summary><b>Kit de captura</b><span aria-hidden="true">+</span></summary><div class="battle-content"><ul><li>Salve antes de interagir com um encontro fixo e leve bolas suficientes.</li><li>Reduza HP com cuidado. False Swipe não acerta Fantasmas normalmente.</li><li>Sono ou paralisia ajudam; veneno, queimadura e outros danos por turno podem derrotar o alvo.</li><li>Quick Ball no primeiro turno; Dusk Ball em cavernas ou à noite; Timer Ball em lutas longas.</li><li>Acompanhe HP e PP para evitar Struggle.</li></ul></div></details>${black2Extra.legends.filter(([,area])=>!ctx.spoilerLocked(ctx.areas.find(a=>a[0]===Black2Bridge.nameToId[area]))).map(([name,area,,text])=>`<details class="battle-card"><summary><b>${esc(name)}</b><span aria-hidden="true">+</span></summary><div class="battle-content"><p>${esc(text)}</p>${link(Black2Bridge.nameToId[area])}</div></details>`).join('')}`;}
 function refresh(){if(!host||host.hidden)return;host.innerHTML=`<header class="plan-intro"><span class="section-index">JOGAR / ACOMPANHAR</span><h1>${tab==='now'?'Sua partida, à mão.':'Prepare o próximo desafio.'}</h1><p>${tab==='now'?'Uma tela curta para consultar enquanto joga.':'Liga, confrontos da história e capturas lendárias.'}</p></header><div class="plan-switch" role="group" aria-label="Modo de jogo"><button type="button" data-playing-tab="now" aria-pressed="${tab==='now'}">Agora</button><button type="button" data-playing-tab="battles" aria-pressed="${tab==='battles'}">Batalhas</button></div><div class="playing-body ${tab==='now'?'playing-now':''}">${tab==='now'?now():battles()}</div>`;}
 function mount(el){host=el;host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.playingTab){tab=b.dataset.playingTab;refresh();}if(b.dataset.playingArea)ctx.openArea(b.dataset.playingArea);if(b.hasAttribute('data-playing-team'))ctx.openTeam();});host.addEventListener('change',e=>{if(e.target.id==='playing-place'){ctx.update({playArea:e.target.value});refresh();}if(e.target.hasAttribute('data-playing-task')){const s=new Set(p().tasks),id=e.target.dataset.playingTask;e.target.checked?s.add(id):s.delete(id);ctx.update({tasks:[...s]});}});host.addEventListener('input',e=>{if(e.target.id==='playing-note'){ctx.update({playNote:e.target.value},false);host.querySelector('#playing-save').textContent=ctx.saveStatus();}});refresh();}
 return {mount,refresh};
}
root.createPlayingGuide=createPlayingGuide;
})(typeof window!=='undefined'?window:globalThis);
