/* Standalone journey for Complete Unova Pokédex Edition. */
(()=>{'use strict';
applyBlack2Hack(black2Data,black2Hack,black2Chapters,black2Extra);
const D=black2Data,C=black2Chapters,X=black2Extra,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),url=encodeURIComponent;
const normalize=p=>({items:Array.isArray(p?.items)?p.items:[],caught:Array.isArray(p?.caught)?p.caught:[],steps:Array.isArray(p?.steps)?p.steps:[],team:Array.isArray(p?.team)?p.team.filter(n=>D.pokemon[n]).slice(0,6):[],plans:Object.fromEntries(Object.entries(p?.plans&&typeof p.plans==='object'?p.plans:{}).filter(([n])=>D.pokemon[n]).map(([n,v])=>[n,{role:String(v?.role||'').slice(0,200),item:String(v?.item||'').slice(0,100),moves:Array.isArray(v?.moves)?v.moves.slice(0,4).map(m=>typeof m==='string'?m:''):[]}])),chapter:Math.max(0,Math.min(21,Number(p?.chapter)||0)),note:String(p?.note||''),difficulty:p?.difficulty||'normal'});
let p=normalize(),query='',page=0,season='',encMethod='',mapZoom=1,areaTab='pokemon';const store=createProgressStore({key:'unova-black2-complete-1.12-v1',normalize,onStatus:s=>$('#save-status').textContent=s.text,onExternal:d=>{p=d;render();}});const save=()=>store.save(p);const link=(text,hash,cls='')=>`<a class="${cls}" href="#${hash}">${esc(text)}</a>`;const stage=a=>{let i=C.findIndex(c=>c.areas.includes(a));return i<0?null:i;};
const method={walk:'Mato ou chão da área','dark-grass':'Mato escuro','grass-spots':'Mato que se mexe','cave-spots':'Nuvem de poeira',surf:'Surf','surf-spots':'Água borbulhando','super-rod':'Pesca com Super Rod','super-rod-spots':'Pesca na água borbulhando',gift:'Presente','gift-egg':'Ovo recebido','only-one':'Encontro fixo','pokeflute':'Encontro fixo',static:'Encontro fixo','hidden-grotto':'Hidden Grotto','npc-trade':'Troca com personagem','bridge-spots':'Sombra na ponte'};
const condition=c=>({'season-spring':'Primavera','season-summer':'Verão','season-autumn':'Outono','season-winter':'Inverno','story-progress-juniper-cave-of-being':'Após encontrar Juniper em Cave of Being','other-regirock-regice-registeel-in-party':'Leve Regirock, Regice e Registeel na equipe','item-lunar-wing':'Tenha Lunar Wing','story-progress-quake-badge':'Após a Quake Badge','special-encounter-couldnt-capture-before':'Reaparece se não foi capturado antes','item-dark-stone':'Tenha Dark Stone','other-captured-reshiram-or-zekrom':'Após capturar Reshiram ou Zekrom'}[c]||(c.startsWith('trade-')?'Ofereça '+c.slice(6):c.startsWith('item-')?'Tenha '+c.slice(5).replaceAll('-',' '):c));
function heading(k,t,d=''){return `<header class="hero"><p class="eyebrow">${esc(k)}</p><h1>${esc(t)}</h1>${d?`<p class="lead">${esc(d)}</p>`:''}</header>`;}
function encounterLabel(e){return e.method==='walk'?(/Cave|Mountain|Passage|Tunnel|Chasm|Tower|Castle/.test(e.area)?'Chão da área':/Desert/.test(e.area)?'Areia':'Mato'):method[e.method]||e.method;}
function encounters(rows){
 if(!rows.length)return '<p class="empty">Nenhum encontro cadastrado para este filtro.</p>';
 const groups=new Map();for(const e of rows){const k=encounterLabel(e);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(e);}
 return `<div class="capture-groups">${[...groups].sort(([a],[b])=>(a==='Mato'?-1:b==='Mato'?1:0)).map(([label,entries],gi)=>{
 const mons=new Map();for(const e of entries){if(!mons.has(e.name))mons.set(e.name,[]);mons.get(e.name).push(e);}
 return `<details class="capture-group" ${gi===0?'open':''}><summary><span>${esc(label)}</span><span class="group-count">${mons.size} Pokémon</span></summary><div class="capture-list">${[...mons].map(([name,es])=>{
 const mon=D.pokemon[name], levels=es.flatMap(e=>e.min!=null?[e.min,e.max]:[]),lo=Math.min(...levels),hi=Math.max(...levels),rates=[...new Set(es.map(e=>e.chance))];
 return `<details class="capture-row"><summary><span class="dex-stamp">${mon?.dex!=null?'#'+String(mon.dex).padStart(3,'0'):'NAC.'}</span><span class="capture-name">${esc(name)}${p.caught.includes(name)?'<span class="caught-mark" aria-label="Capturado"> ✓</span>':''}<small>${esc(mon?.types.join(' / ')||'')}</small></span><span class="capture-metrics">${levels.length?`Nv. ${lo}${hi!==lo?'–'+hi:''}`:''}${rates.length===1&&rates[0]!=null?`<small>${rates[0]}%</small>`:''}</span><span class="row-chevron" aria-hidden="true">⌄</span></summary><div class="capture-detail">${es.map(e=>`<div class="capture-location"><b>${esc(e.zone||e.area)}</b><p>${e.conditions?.length?esc(e.conditions.map(condition).join(' · ')):'Sem condição adicional documentada.'}${e.post?' · Pós-jogo':''}</p><p>${e.min==null?'Nível não documentado.':`Nv. ${e.min}${e.max!==e.min?'–'+e.max:''}.`} ${e.chance==null?'Taxa não confirmada.':`Chance: ${e.chance}%.`}</p>${e.note?`<p>${esc(e.note)}</p>`:''}</div>`).join('')}<div class="capture-actions"><label class="checkline"><input type="checkbox" data-caught="${esc(name)}" ${p.caught.includes(name)?'checked':''}>Capturei</label>${link('Ver Pokémon →','dex/'+url(name))}</div></div></details>`;
 }).join('')}</div></details>`;
 }).join('')}</div>`;
}
function items(a){return [...D.machines.filter(x=>x.area===a).map(x=>[x.code+' · '+x.name,x.area,x.note]),...X.items.filter(x=>x[1]===a)].map(x=>`<article class="entry"><label class="checkline"><input type="checkbox" data-item="${esc(x[1]+'|'+x[0])}" ${p.items.includes(x[1]+'|'+x[0])?'checked':''}>${esc(x[0])}</label><p>${esc(x[2])}</p></article>`).join('')||'<p>Sem itens documentados aqui por enquanto.</p>';}
function play(id){const i=C.findIndex(c=>c.id===id);if(i<0)return heading('COMPLETE UNOVA · v1.12','Sua jornada', 'Detonado, capturas e itens da Complete Unova v1.12.')+`<section class="resume"><p class="eyebrow">ESTOU JOGANDO AGORA</p><h2>${esc(C[p.chapter].title)}</h2>${link('Continuar o guia →','play/'+C[p.chapter].id,'button primary')}</section><label class="card">Lembrete para a próxima sessão<textarea data-note placeholder="Onde parei, o que quero capturar…">${esc(p.note)}</textarea></label><div class="chapter-list">`+C.map((c,n)=>link(`${String(n+1).padStart(2,'0')} · ${c.title} · ${c.steps.filter(s=>p.steps.includes(s.id)).length}/${c.steps.length}`,'play/'+c.id,'chapter-link')).join('')+'</div>';
const c=C[i];return `<div class="reader">${link('← Todos os capítulos','play')}`+heading(`CAPÍTULO ${i+1} · ${c.post?'PÓS-JOGO':'AVENTURA'}`,c.title,c.goal)+`<button data-stage="${i}">Estou nesta etapa</button><p class="reading-progress">${c.steps.filter(s=>p.steps.includes(s.id)).length} de ${c.steps.length} passos concluídos</p>`+c.steps.map((s,n)=>`<article class="step ${p.steps.includes(s.id)?'checked':''}"><label><input type="checkbox" data-step="${s.id}" ${p.steps.includes(s.id)?'checked':''}><span>Passo ${n+1} · ${esc(s.title)}</span></label><p>${esc(s.text)}</p></article>`).join('')+['prep','optional','lost'].map((k,n)=>`<details class="card"><summary>${['Antes de continuar','Exploração opcional','Me perdi. Para onde vou?'][n]}</summary><p>${esc(c[k])}</p></details>`).join('')+`<details class="card"><summary>Áreas, capturas e itens deste capítulo</summary>${c.areas.map(a=>link(a,'map/'+url(a),'chapter-link')).join('')}</details><p class="source"><a href="${esc(c.source)}" target="_blank" rel="noopener">Referência do percurso original</a> · Texto próprio. Consulte as mudanças da hack na aba Mais.</p><footer class="reader-footer">${i?link('← Anterior','play/'+C[i-1].id):''}${i<21?link('Próximo →','play/'+C[i+1].id):''}</footer></div>`;}
const areas=[...new Set([...D.encounters.map(x=>x.area),...C.flatMap(c=>c.areas)])].sort();
function map(a){const points=X.points,all=D.encounters.filter(e=>e.area===a),filtered=all.filter(e=>!season||!e.conditions.some(c=>c.startsWith('season-'))||e.conditions.includes('season-'+season));return heading('UNOVA / BLACK 2',a||'Mapa de Unova')+`<details class="atlas-panel" ${a?'':'open'}><summary>${a?'Abrir mapa':'Explorar a região'}</summary><div class="map-controls"><button data-zoom="1">Visão geral</button><button data-zoom="2">Ampliar mapa</button></div><div class="map-frame"><svg style="width:${mapZoom*100}%;min-width:0" viewBox="0 0 1712 1080" role="img" aria-label="Mapa esquemático de Unova"><image href="black2-base.svg" width="1712" height="1080"/>${X.paths.map(path=>`<polyline points="${path.filter(n=>points[n]).map(n=>points[n].join(',')).join(' ')}" fill="none" stroke="#d5a95c" stroke-width="12" stroke-linejoin="round"/>`).join('')}${Object.entries(points).map(([n,v])=>`<a href="#map/${url(n)}"><title>${esc(n)}</title><circle cx="${v[0]}" cy="${v[1]}" r="24" fill="transparent"/><circle cx="${v[0]}" cy="${v[1]}" r="10" fill="${n===a?'#b85532':'#173c3c'}" stroke="#fff" stroke-width="4"/>${n===a||/City|Town/.test(n)?`<text x="${v[0]>1500?v[0]-16:v[0]+16}" text-anchor="${v[0]>1500?'end':'start'}" y="${v[1]-16}" font-size="19" fill="#173c3c">${esc(n)}</text>`:''}</a>`).join('')}</svg></div></details><label class="area-picker">Ir para<select data-area><option value="">Escolher área…</option>${areas.map(n=>`<option ${n===a?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`+(a?`<section id="area"><div class="area-meta"><span>${new Set(all.map(e=>e.name)).size} Pokémon registrados</span>${stage(a)!=null?link('Capítulo '+(stage(a)+1)+' →','play/'+C[stage(a)].id):''}</div><div class="area-tabs" aria-label="Conteúdo da área"><button data-area-tab="pokemon" aria-pressed="${areaTab==='pokemon'}">Pokémon</button><button data-area-tab="items" aria-pressed="${areaTab==='items'}">Itens e TMs</button></div>${areaTab==='items'?`<div class="area-items">${items(a)}</div>`:`<div class="capture-toolbar"><span>Toque no Pokémon para ver os detalhes.</span><label><span class="sr-only">Estação</span><select data-season aria-label="Estação"><option value="">Todas as estações</option>${[['spring','Primavera'],['summer','Verão'],['autumn','Outono'],['winter','Inverno']].map(([v,n])=>`<option value="${v}" ${season===v?'selected':''}>${n}</option>`).join('')}</select></label></div>${encounters(filtered)}<details class="data-note"><summary>Sobre os dados da hack</summary><p>Taxas são específicas do método e das condições de cada encontro. Dados ausentes ficam em aberto; os níveis mantidos de encontros não substituídos vêm do jogo-base. Alterações detalhadas usam os documentos v1.11 e as regras v1.12 informadas.</p></details>`}</section>`:'');}
function family(n){const seen=new Set();while(n&&D.pokemon[n]&&!seen.has(n)){seen.add(n);n=D.pokemon[n].parent;}return [...seen];}
function timeline(n){const names=family(n),es=D.encounters.filter(e=>names.includes(e.name)).map(e=>({...e,s:e.post?Math.max(15,stage(e.area)??15):stage(e.area)})).filter(e=>e.s!=null).sort((a,b)=>a.s-b.s);const e=es[0];return e?`Primeiro registro do catálogo: ${e.name}, ${e.area} · capítulo ${e.s+1}. ${e.s<=p.chapter?'A área aparece na sua etapa; o encontro ainda pode exigir condições adicionais.':'Mais adiante na jornada.'} Confira o método e os requisitos na área.`:'Ainda não há um local de obtenção confirmado neste catálogo.';}
function dex(n){if(D.pokemon[n]){const m=D.pokemon[n];return link('← Pokédex','dex')+heading(m.dex!=null?'UNOVA #'+String(m.dex).padStart(3,'0'):'POKÉDEX NACIONAL #'+m.id,n,m.types.join(' / '))+`<label class="checkline"><input type="checkbox" data-caught="${esc(n)}" ${p.caught.includes(n)?'checked':''}>Já capturei</label><p class="timeline">${esc(timeline(n))}</p><details class="card" open><summary>Evoluções</summary>${D.evolutions.filter(e=>e.fromSpecies===n||e.toSpecies===n).map(e=>`<p><b>${esc(e.fromSpecies)} → ${esc(e.toSpecies)}</b><br>${esc(e.condition)} ${e.hack?'<span class="badge">Hack</span>':''}</p>`).join('')||'<p>Sem evolução cadastrada.</p>'}</details><details class="card" open><summary>Onde encontrar</summary>${encounters(D.encounters.filter(e=>e.name===n))}</details>`;}const list=Object.entries(D.pokemon).filter(([name,m])=>(m.dex!=null||query)&&(`${name} ${m.dex??''}`).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a[1].dex??9999)-(b[1].dex??9999));return heading('CATÁLOGO','Pokédex de Unova',`${p.caught.length} capturados neste aparelho. Pesquise também Pokémon fora da Pokédex regional.`)+`<form id="search" class="searchline"><input aria-label="Buscar Pokémon" name="q" value="${esc(query)}" placeholder="Nome ou número de Unova"><button>Buscar</button></form><div class="dex-list">${list.slice(page*30,page*30+30).map(([name,m])=>link(`${m.dex!=null?'#'+String(m.dex).padStart(3,'0'):'Nac. '+m.id} · ${name}${p.caught.includes(name)?' ✓':''}`,'dex/'+url(name),'dex-card')).join('')}</div><div class="pagination"><button data-page="-1" ${page===0?'disabled':''}>Anterior</button><span>${page+1} / ${Math.max(1,Math.ceil(list.length/30))}</span><button data-page="1" ${(page+1)*30>=list.length?'disabled':''}>Próxima</button></div>`;}
function more(){return heading('SEU CADERNO','Guia de batalha e extras','Complete Unova Pokédex Edition v1.12 · base Black 2')+`<section class="card"><h2>Batalhas importantes</h2><p>A hack aumenta as equipes: Marlon tem 4 Pokémon no Easy/Normal e 5 no Challenge; a Elite Four tem 5 ou 6. Os times completos alterados ainda não estão confirmados. As dicas abaixo orientam o preparo, mas não garantem os golpes dos adversários.</p>${Object.entries(X.battleTips).map(([n,t])=>`<details><summary>${esc(n)}</summary><p>${esc(t)}</p></details>`).join('')}</section><section class="card"><h2>Lendários e encontros especiais</h2><p>Salve antes dos encontros fixos. Leve um Pokémon que cause sono ou paralisia e reduza o HP sem nocautear. Confira o método: a hack também adiciona encontros selvagens no pós-jogo.</p>${X.legends.map(x=>`<details><summary>${esc(x[0])} · ${esc(x[1])}</summary><p>${esc(x[3])}</p>${link('Ver área','map/'+url(x[1]))}</details>`).join('')}</section><section class="card"><h2>O que muda nesta edição</h2><p>As evoluções por troca agora têm alternativas por nível, item equipado ou amizade. Leafeon usa Leaf Stone; Glaceon usa Dawn Stone, adicionada na Route 16. As páginas dos Pokémon mostram os métodos específicos.</p><p>As Keys de dificuldade e de área estão liberadas desde o início. Nidorina e Nidoqueen podem procriar. Cover Fossil e Plume Fossil custam 7.000 em Nacrene. Elekid pode carregar Electirizer e Magby, Magmarizer (5% cada). As formas de Kyurem carregam Salac Berry.</p><p>As regras v1.12 fornecidas por você são a base desta edição. Os detalhes de encontros e golpes usam a documentação pública v1.11; diferenças não documentadas não são tratadas como confirmadas. Os times exatos da hack e a lista completa de itens comuns ainda precisam de conferência.</p>${black2Hack.sources.map(s=>`<p><a target="_blank" rel="noopener" href="${esc(s)}">Consultar documentação</a></p>`).join('')}</section><section class="card"><h2>Progresso</h2><p>Salvo automaticamente neste navegador, com uma cópia de recuperação no aparelho. Pokémon Black tem um progresso separado. Limpar os dados do site também apaga esses registros.</p><button id="export">Baixar uma cópia opcional</button><label>Restaurar cópia<input id="import" type="file" accept="application/json"></label></section>`;}
const nav=[['play','Jogar','M4 4h16v16H4z M8 4v16'],['map','Mapa','m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3z M9 3v15 M15 6v15'],['dex','Pokédex','M3 3h18v18H3z M7 8h10 M7 13h10 M7 17h5'],['more','Mais','M5 12h1 M11 12h1 M17 12h1']];
function render(){const oldY=window.scrollY;let [view='play',arg='']=location.hash.slice(1).split('/');if(view==='team'){view='play';history.replaceState(null,'','#play');}try{arg=decodeURIComponent(arg);}catch{arg='';}$('#content').innerHTML=view==='map'?map(arg):view==='dex'?dex(arg):view==='more'?more():play(arg);$('.dock').innerHTML=nav.map(([id,t,path])=>`<a href="#${id}" ${view===id?'aria-current="page"':''}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="${path}"/></svg><span>${t}</span></a>`).join('');window.scrollTo(0,oldY);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.zoom){mapZoom=+b.dataset.zoom;const y=window.scrollY;render();window.scrollTo(0,y);}if(b.dataset.stage!==undefined){p.chapter=+b.dataset.stage;save();b.textContent='Etapa atual salva ✓';}if(b.dataset.areaTab){areaTab=b.dataset.areaTab;render();}if(b.dataset.page){page+=+b.dataset.page;render();window.scrollTo(0,0);}if(b.id==='export'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({...p,edition:black2Hack.id})],{type:'application/json'}));a.download='unova-black2-progresso.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}});
document.addEventListener('input',e=>{const t=e.target;if(t.hasAttribute('data-note')){p.note=t.value;save();}});
document.addEventListener('change',async e=>{const t=e.target;for(const [attr,key]of [['step','steps'],['caught','caught'],['item','items']])if(t.dataset[attr]){p[key]=p[key].filter(x=>x!==t.dataset[attr]);if(t.checked)p[key].push(t.dataset[attr]);save();if(attr==='step'){t.closest('.step')?.classList.toggle('checked',t.checked);const current=C.find(c=>c.steps.some(s=>s.id===t.dataset.step));if(current&&$('.reading-progress'))$('.reading-progress').textContent=current.steps.filter(s=>p.steps.includes(s.id)).length+' de '+current.steps.length+' passos concluídos';}}if(t.hasAttribute('data-area')){areaTab='pokemon';encMethod='';location.hash='map/'+url(t.value);}if(t.hasAttribute('data-season')){season=t.value;render();}if(t.hasAttribute('data-method')){encMethod=t.value;render();}if(t.id==='import'&&t.files[0]){try{const v=JSON.parse(await t.files[0].text());if(v.edition!==black2Hack.id||!Array.isArray(v.caught))throw Error();if(confirm('Restaurar esta cópia substituindo o progresso de Black 2 neste aparelho?')){p=normalize(v);await save();render();}}catch{alert('Esta cópia não pertence a esta edição de Black 2.');}}});
document.addEventListener('change',e=>{
 const name=e.target.dataset.caught;if(!name)return;
 for(const box of document.querySelectorAll('[data-caught]'))if(box.dataset.caught===name)box.checked=e.target.checked;
 for(const row of document.querySelectorAll('.capture-row')){
  if(row.querySelector('[data-caught]')?.dataset.caught!==name)continue;
  row.querySelector('.caught-mark')?.remove();
  if(e.target.checked){const mark=document.createElement('span');mark.className='caught-mark';mark.textContent=' ✓';mark.setAttribute('aria-label','Capturado');row.querySelector('.capture-name').prepend(mark);}
 }
});
document.addEventListener('submit',e=>{if(e.target.id==='search'){e.preventDefault();query=new FormData(e.target).get('q').trim();page=0;render();}});
window.addEventListener('hashchange',()=>{try{localStorage.setItem('unova-black2-last-page',location.hash);}catch{}render();window.scrollTo(0,0);});try{localStorage.setItem('unova-last-game','black2');if(!location.hash&&localStorage.getItem('unova-black2-last-page'))history.replaceState(null,'',localStorage.getItem('unova-black2-last-page'));}catch{}store.load().then(v=>{p=normalize(v);render();}).catch(()=>{render();$('#save-status').textContent='Não foi possível recuperar o progresso.';});
})();
