/* Editorial notes and map anchors for Black 2. Stage means chapter, not badge count. */
const black2Extra = {
 items:[
 ['Exp. Share','Castelia City','Converse com o funcionário na entrada da Battle Company. O portador recebe parte da experiência mesmo sem participar da luta.',4],
 ['Lucky Egg','Celestial Tower','Juniper entrega no primeiro andar. Equipe no integrante que estiver treinando.',10],
 ['Lunar Wing','Strange House','Explore o subsolo e volte aos cômodos do andar superior conforme os móveis mudam. Leve depois a Marvelous Bridge para Cresselia.',11],
 ['Magma Stone','Route 18','Procure o item na parte elevada da ilha durante a exploração do pós-jogo. Leve à câmara de Heatran em Reversal Mountain.',21],
 ['Dark Stone','N’s Castle','Vença N e seu Zekrom no pós-jogo. A pedra permite o encontro de captura em Dragonspiral Tower.',19],
 ['DNA Splicers','Giant Chasm','Recolha após a captura de Kyurem no pós-jogo. Permite fundir Kyurem ao dragão compatível.',19],
 ['Soothe Bell','Nimbasa City','Mostre à senhora de uma casa da cidade um Pokémon com amizade alta. Útil para planejar evoluções por amizade.',6],
 ['Eviolite','Castelia City','No prédio da rua norte, mostre ao cientista uma Pokédex com pelo menos 40 espécies vistas. Fortalece as defesas de Pokémon que ainda podem evoluir.',4],
 ['Dusk Stone','Strange House','Explore os cômodos e o subsolo enquanto os móveis mudam de lugar. É um recurso de evolução, não um item de batalha para Chandelure.',11],
 ['Shiny Stone','Route 6','Procure na parte nordeste da rota, perto da região do laboratório e das casas. Confira os desvios antes de entrar em Chargestone.',9],
 ['Sun Stone','Nimbasa City','Receba na casa a noroeste do Centro Pokémon.',6],
 ['Heart Scale','Pokémon World Tournament','O lembrador de golpes consome uma Heart Scale por serviço. Traga as que encontrar na exploração.',8],
 ['Red Shard','Driftveil City','Moeda do tutor local. Veja a quantidade exigida por golpe no plano da equipe.',7],
 ['Blue Shard','Lentimas Town','Moeda do tutor local. Veja a quantidade exigida por golpe no plano da equipe.',11],
 ['Yellow Shard','Humilau City','Moeda do tutor local. Veja a quantidade exigida por golpe no plano da equipe.',13],
 ['Green Shard','Nacrene City','Moeda do tutor local no pós-jogo. Veja a quantidade exigida por golpe no plano da equipe.',20],
 ['Super Rod','Aspertia City','Receba de Cedric Juniper na sequência em casa após os créditos. A pesca não fica disponível durante a história principal.',16],
 ['Colress MCHN','Route 22','Colress entrega perto de Terrakion. Use no Crustle que bloqueia a saída leste de Seaside Cave.',13],
 ['Bicycle','Castelia City','Receba do palhaço ao chegar à via principal vindo do cais.',4],
 ['Permit','Nuvema Town','Juniper entrega ao cumprir a exigência de espécies vistas da Pokédex regional. Libera Nature Preserve por Mistralton.',22]
 ],
 returns:[
 ['Margens do início','Route 19','surf',9,'Surf abre a margem e os itens antes separados pela água.'],
 ['Caverna de Axew','Mistralton Cave','surf',9,'Chegue pelo rio da Route 6. Leve Strength e, para enxergar melhor, Flash.'],
 ['Exploração do rancho','Floccesy Ranch','surf',9,'Volte para as tabelas de Surf e as margens que não eram acessíveis no início.'],
 ['Trio dos lagos','Cave of Being','waterfall',16,'Use Surf e Waterfall na Route 20. A cena com Juniper é requisito para os três encontros.'],
 ['Ruínas submersas','Undella Bay','dive',17,'Dive chega no pós-jogo. Planeje cada entrada respeitando o limite de passos.'],
 ['Cresselia','Marvelous Bridge','lunar',18,'Leve a Lunar Wing de Strange House; salve antes do encontro.'],
 ['Zekrom','Dragonspiral Tower','dark',19,'Leve a Dark Stone recebida após a batalha com N.'],
 ['Kyurem','Giant Chasm','zekrom',19,'Depois de capturar Zekrom, retorne à câmara profunda.'],
 ['Heatran','Reversal Mountain','magma',22,'Leve a Magma Stone da Route 18 para a câmara ligada a Heatran.'],
 ['Pesca no rancho','Floccesy Ranch','rod',16,'Use a Super Rod. A água com ondulação tem uma tabela diferente.']
 ],
 flags:{surf:'Tenho Surf',strength:'Tenho Strength',waterfall:'Tenho Waterfall',dive:'Tenho Dive',rod:'Tenho Super Rod',lunar:'Peguei a Lunar Wing',dark:'Recebi a Dark Stone',zekrom:'Capturei Zekrom',magma:'Peguei a Magma Stone'},
 battleTips:{
 Cheren:'Work Up aumenta o poder dos ataques. Evite gastar vários turnos sem causar dano. Uma Oran Berry equipada ajuda a manter o ritmo. Riolu só ajuda com dano Lutador quando já conhece o golpe adequado.',
 Roxie:'Koffing tem Levitate: Terrestre comum não acerta. Magnemite resiste bem aos ataques de Veneno, mas isso não torna todos os golpes inimigos inofensivos. Cure veneno antes de receber Venoshock.',
 Burgh:'Leavanny é muito vulnerável a Fogo e Voador. Dwebble, porém, tem ataque de Pedra e pode sobreviver com Sturdy. Alterne o atacante em vez de confiar num único tipo.',
 Elesa:'Terrestre impede Volt Switch de causar dano e trocar o usuário, mas Emolga é imune a Terrestre. Prepare um segundo atacante. Zebstrika pode usar Flame Charge contra Planta e Aço.',
 Clay:'Não permita que Excadrill acumule aumentos. Um golpe de Água forte costuma ser útil. Krokorok pode reduzir Ataque com Intimidate; um atacante especial contorna essa redução.',
 Skyla:'Swanna é muito vulnerável a Elétrico. Skarmory tem Defesa física alta; considere dano especial. Confira também a cobertura de cada inimigo abaixo.',
 Drayden:'Haxorus com Dragon Dance se torna uma ameaça rapidamente. Ataque ou atrapalhe a preparação. Gelo funciona bem, mas não existe tipo Fada nesta geração.',
 Marlon:'Carracosta pode sobreviver por Sturdy e usar Shell Smash. Planeje o segundo turno. Jellicent recupera HP; tenha dano consistente. Scald pode queimar e enfraquecer atacantes físicos.',
 Shauntal:'Golpes Normal e Lutador comuns não acertam Fantasmas. Sombrio e Fantasma ajudam, mas confira a cobertura adversária. Não presuma que todos têm as mesmas fraquezas secundárias.',
 Grimsley:'Lutador atinge bem a equipe, especialmente Bisharp. Confira Aerial Ace e golpes que podem punir seu atacante Lutador. Intimidate de Krookodile reduz dano físico.',
 Caitlin:'Sombrio evita golpes Psíquicos, mas a cobertura pode acertá-lo. Reuniclus pode recuperar HP. Evite permitir vários Calm Mind e considere golpes físicos contra esse aumento de Defesa Especial.',
 Marshal:'Sawk com Sturdy pode sobreviver a um golpe. Confira os ataques de Pedra antes de colocar um Voador. Não deixe um integrante com poucos HP em campo esperando uma vitória automática por tipo.',
 Iris:'Prepare respostas para Dragão, Água/Gelo e Aço/Pedra. Haxorus tem Focus Sash e Dragon Dance na primeira luta: dano residual controlado ou uma resposta para o turno seguinte ajudam. A revanche tem recursos diferentes; leia o painel correspondente.',
 Ghetsis:'Cure Toxic para não ser desgastado por Cofagrigus. Planta pressiona Seismitoad; Terrestre ajuda contra Drapion. Eelektross com Levitate não tem a fraqueza Terrestre habitual. Hydreigon tem cobertura variada: confira os quatro golpes.',
 Colress:'Não trate toda a equipe como Aço: Beheeyem é Psíquico. Ataques de Fogo e Terrestre ajudam contra vários integrantes, mas habilidades e Sturdy podem impedir a vitória em um único golpe.'
 },
 legends:[
 ['Cobalion','Route 13',12,'Encontro fixo durante a história. Salve antes de interagir. Justified aumenta seu Ataque quando recebe um golpe Sombrio.'],
 ['Virizion','Route 11',12,'Encontro fixo. Evite Voador para enfraquecer: causa dano quádruplo. Não é preciso encontrar Cobalion em Mistralton Cave como em Black.'],
 ['Terrakion','Route 22',13,'Encontro fixo perto de Colress. Receber a máquina não exige capturá-lo. Prepare dano controlado.'],
 ['Zekrom','Dragonspiral Tower',19,'No pós-jogo, vença N em seu castelo e leve a Dark Stone ao topo da torre. Essa é a captura do dragão de N em Black 2.'],
 ['Kyurem','Giant Chasm',19,'Capture Zekrom primeiro e volte à câmara profunda. A luta da história contra Black Kyurem não permite captura.'],
 ['Cresselia','Marvelous Bridge',18,'Leve a Lunar Wing obtida em Strange House. O encontro acontece na ponte.'],
 ['Heatran','Reversal Mountain',22,'Leve a Magma Stone da Route 18 à câmara própria na montanha. Cuidado com a fraqueza quádrupla a Terrestre.'],
 ['Latios','Dreamyard',20,'Siga Latios pelas ruínas até o ponto final. Black 2 tem Latios; Latias pertence à outra versão.'],
 ['Regirock','Underground Ruins',17,'Do centro do olho no chão, vá seis passos ao sul e nove a leste e examine o piso. Entre na câmara depois de acionar o interruptor.'],
 ['Registeel','Iron Room',17,'Black 2 libera a Iron Key após Regirock. Ative a chave no Unova Link para visitar a sala correspondente.'],
 ['Regice','Glacier Room',17,'Exige a Iceberg Key recebida de White 2. Não fica disponível apenas com os recursos de uma partida isolada de Black 2.'],
 ['Regigigas','Twist Mountain',17,'Tenha Regirock, Regice e Registeel na equipe para despertar o encontro no fundo da montanha.'],
 ['Uxie','Nacrene City',20,'Primeiro complete o evento de Cave of Being com Juniper. Depois visite a área do museu.'],
 ['Mesprit','Celestial Tower',16,'Primeiro complete o evento de Cave of Being com Juniper. Depois procure o topo de Celestial Tower.'],
 ['Azelf','Route 23',16,'Primeiro complete o evento de Cave of Being com Juniper. Depois procure a plataforma elevada da Route 23.']
 ],
 points:{'Aspertia City':[130,960],'Route 19':[205,900],'Floccesy Town':[280,900],'Route 20':[360,900],'Floccesy Ranch':[360,790],'Virbank City':[480,900],'Virbank Complex':[480,1000],'Pokéstar Studios':[480,820],'Castelia City':[880,832],'Route 4':[880,685],'Desert Resort':[760,650],'Relic Castle':[760,600],'Join Avenue':[880,620],'Nimbasa City':[880,570],'Route 5':[700,570],'Driftveil Drawbridge':[610,570],'Driftveil City':[490,570],'Pokémon World Tournament':[490,680],'Relic Passage':[620,730],'Route 6':[367,490],'Mistralton Cave':[420,440],'Chargestone Cave':[275,492],'Mistralton City':[260,410],'Route 7':[365,328],'Celestial Tower':[365,255],'Lentimas Town':[1100,410],'Reversal Mountain':[1280,410],'Strange House':[1150,475],'Undella Town':[1498,410],'Route 13':[1386,327],'Lacunosa Town':[1268,246],'Route 12':[1188,246],'Village Bridge':[1112,246],'Route 11':[1027,246],'Opelucid City':[878,246],'Route 9':[787,246],'Humilau City':[1600,185],'Route 22':[1480,170],'Route 21':[1590,290],'Seaside Cave':[1570,355],'Giant Chasm':[1323,157],'Route 23':[1370,90],'Victory Road':[1490,90],'Pokémon League':[1580,50],'Route 16':[1016,570],'Lostlorn Forest':[973,505],'Undella Bay':[1618,465],'Route 14':[1377,489],'Abundant Shrine':[1360,410],'Black City':[1268,570],'Route 15':[1207,570],'Marvelous Bridge':[1115,570],'Nacrene City':[1352,750],'Pinwheel Forest':[1294,812],'Skyarrow Bridge':[1135,767],'Route 3':[1436,750],'Wellspring Cave':[1439,690],'Striaton City':[1521,750],'Dreamyard':[1620,749],'Route 2':[1533,819],'Accumula Town':[1550,883],'Route 1':[1549,948],'Nuvema Town':[1550,1018],'Route 17':[1380,949],'Route 18':[1240,1007],'P2 Laboratory':[1380,864],'Icirrus City':[488,246],'Moor of Icirrus':[593,183],'Route 8':[593,246],'Tubeline Bridge':[702,246],'Dragonspiral Tower':[435,157],'Twist Mountain':[433,287],'Clay Tunnel':[490,475],'Anville Town':[100,156]},
 paths:[['Aspertia City','Route 19','Floccesy Town','Route 20','Virbank City','Castelia City','Route 4','Join Avenue','Nimbasa City','Route 5','Driftveil Drawbridge','Driftveil City','Route 6','Chargestone Cave','Mistralton City','Route 7','Celestial Tower'],['Route 20','Floccesy Ranch'],['Virbank Complex','Virbank City','Pokéstar Studios'],['Route 4','Desert Resort','Relic Castle'],['Driftveil City','Pokémon World Tournament','Relic Passage'],['Route 6','Mistralton Cave'],['Lentimas Town','Reversal Mountain','Undella Town','Route 13','Lacunosa Town','Route 12','Village Bridge','Route 11','Opelucid City','Route 9'],['Lentimas Town','Strange House'],['Undella Town','Seaside Cave','Route 21','Humilau City','Route 22','Giant Chasm','Route 23','Victory Road','Pokémon League'],['Nimbasa City','Route 16','Marvelous Bridge','Route 15','Black City','Route 14','Undella Town'],['Route 16','Lostlorn Forest'],['Castelia City','Skyarrow Bridge','Pinwheel Forest','Nacrene City','Route 3','Striaton City','Dreamyard'],['Striaton City','Route 2','Accumula Town','Route 1','Nuvema Town'],['Route 1','Route 17','Route 18'],['Route 17','P2 Laboratory'],['Route 3','Wellspring Cave'],['Route 9','Tubeline Bridge','Route 8','Icirrus City','Dragonspiral Tower'],['Icirrus City','Twist Mountain','Route 7'],['Route 8','Moor of Icirrus'],['Undella Town','Undella Bay'],['Route 14','Abundant Shrine']]
};
