/* Local, optional team goals. A plan never changes capture checkmarks. */
(function(root){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typePT={Normal:'Normal',Fighting:'Lutador',Flying:'Voador',Poison:'Veneno',Ground:'Terra',Rock:'Pedra',Bug:'Inseto',Ghost:'Fantasma',Steel:'Aço',Fire:'Fogo',Water:'Água',Grass:'Planta',Electric:'Elétrico',Psychic:'Psíquico',Ice:'Gelo',Dragon:'Dragão',Dark:'Sombrio'};
function typeMultiplier(chart,attack,types){return types.reduce((factor,t)=>factor*(chart[attack]?.[t]??1),1);}
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function family(data,name){const out=[],seen=new Set();while(data.pokemon[name]&&!seen.has(name)){seen.add(name);out.unshift(name);name=data.pokemon[name].parent;}return out;}
function moveOptions(data,name){const rows=new Map();for(const species of family(data,name))for(const [move,method,level] of data.pokemon[species].moves){if(!rows.has(move))rows.set(move,[]);rows.get(move).push({species,method,level});}return rows;}
function normalizeTeamPlan(value,species,data,itemNames){const clean={};if(!value||typeof value!=='object'||Array.isArray(value))return clean;for(const name of species){const v=value[name];if(!v||typeof v!=='object')continue;const legal=moveOptions(data,name);clean[name]={current:species.includes(v.current)?v.current:'',level:Number.isInteger(v.level)&&v.level>=1&&v.level<=100?v.level:0,role:typeof v.role==='string'?v.role.slice(0,80):'',item:itemNames.includes(v.item)?v.item:'',moves:Array.isArray(v.moves)?[...new Set(v.moves.filter(m=>legal.has(m)))].slice(0,4):[]};}return clean;}
function evolutionWarning(data,name,move,current=''){const rows=moveOptions(data,name).get(move)||[];const direct=rows.filter(r=>r.species===name);const earlier=rows.filter(r=>r.species!==name&&r.method===1);if(earlier.length&&!direct.length)return `Aprenda ${move} com ${earlier.map(r=>r.species+' no Nv. '+r.level).join(' ou ')} antes de evoluir. O relembrador da forma final não recupera automaticamente golpes exclusivos da pré-evolução.`;const earlierLevel=earlier.filter(r=>!current||r.species===current);const later=direct.filter(r=>r.method===1);if(earlierLevel.length&&later.length&&Math.min(...earlierLevel.map(r=>r.level))<Math.min(...later.map(r=>r.level)))return `${move} chega antes em ${earlierLevel.map(r=>r.species+' (Nv. '+r.level+')').join(' ou ')}. Evoluir pode adiar esse golpe; confira os níveis abaixo.`;return '';}
function createTeamPlanner(ctx){
 const {data,species,areas,items,guide,getProgress,update}=ctx;
 const itemNames=[...new Set(Object.values(items).flat().filter(r=>r.kind==='item'&&!r.unavailable).map(r=>r.name))].sort();
 let host,openName='',tab='ideal';
 const options=(list,selected,blank)=>`<option value="">${esc(blank)}</option>`+list.map(n=>`<option value="${esc(n)}" ${n===selected?'selected':''}>${esc(n)}</option>`).join('');
 const location=(id,label)=>`<button type="button" class="text-link" data-plan-area="${esc(id)}">${esc(label||areas.find(a=>a[0]===id)?.[1]||id)} ↗</button>`;
 const stageOf=r=>r.area[5]==='post'?9:(ctx.stage[r.area[0]]??9);
 const step=r=>stageOf(r)===9?'Pós-jogo':stageOf(r)===0?'Início da jornada':`A partir de ${stageOf(r)} insígnia${stageOf(r)>1?'s':''} (estimativa)`;
 function acquisition(name){const chain=family(data,name),rows=chain.flatMap(n=>guide.routes(n).map(r=>({...r,species:n}))).filter(r=>r.area[0]!=='swords').sort((a,b)=>stageOf(a)-stageOf(b));return {chain,rows};}
 function itemRows(name){return areas.flatMap(a=>(items[a[0]]||[]).filter(r=>r.name===name).map(row=>({area:a,row}))).filter(r=>!ctx.spoilerLocked(r.area));}
 function itemHTML(name){const rows=itemRows(name);return rows.slice(0,3).map(({area,row})=>`<div class="plan-step"><b>${esc(row.code||row.name)}</b>${location(area[0])}<p>${esc(row.where)}</p>${row.requirements?.length?`<small>${esc(row.requirements.join(' · '))}</small>`:''}${row.unavailable?'<small>Indisponível em uma partida comum.</small>':''}${row.price?`<small>${esc(row.price)}</small>`:''}<small>${getProgress().collectedItems.includes(row.id)?'Você marcou este registro como obtido.':'Registro ainda não marcado.'}</small></div>`).join('')||'<p>Sem localização cadastrada com os filtros atuais. Isso não comprova que o item seja impossível.</p>';}
 function moveHTML(name,move,v){const rows=moveOptions(data,name).get(move)||[],warning=evolutionWarning(data,name,move,v.current);const machines=areas.flatMap(a=>(items[a[0]]||[]).filter(r=>r.move===move||r.name===move).map(row=>({area:a,row}))).filter(r=>!ctx.spoilerLocked(r.area));return `<div class="plan-step"><b>${esc(move)}</b>${warning?`<p class="plan-warning">${esc(warning)}</p>`:''}<ul>${rows.map(r=>`<li>${esc(r.species)}: ${esc(data.methods[r.method]||'Método especial')}${r.method===1?' · Nv. '+r.level:''}${r.method===1&&r.level<=v.level&&r.species===v.current?' · nível informado já alcançado':''}</li>`).join('')}</ul>${rows.some(r=>r.method===2)?'<small>Reprodução exige compatibilidade dos pais; um registro de golpe não garante que sua equipe atual já possa produzi-lo.</small>':''}${rows.some(r=>r.method===3)?'<small>Confira o tutor e suas condições em Ferramentas → Serviços úteis.</small>':''}${machines.slice(0,2).map(r=>location(r.area[0],r.row.code+' · '+r.area[1])).join('')}</div>`;}
 function viability(name){const a=acquisition(name),r=a.rows[0],v=getProgress().teamPlan[name]||{};const rules=data.evolutions.filter(e=>a.chain.includes(e.fromSpecies)&&a.chain.includes(e.toSpecies));const flags=[];if(!r)flags.push(ctx.acquisition[name]||'Obtenção ainda não confirmada pelos registros.');else{flags.push(stageOf(r)===9?'A primeira obtenção cadastrada é no pós-jogo.':'Há uma rota de obtenção durante a história; confira os requisitos abaixo.');if(r.lock)flags.push(r.lock);}if(rules.some(e=>/troca/i.test(e.condition)))flags.push('A evolução planejada exige troca.');if((v.moves||[]).some(m=>(moveOptions(data,name).get(m)||[]).some(r=>r.method===2)))flags.push('Há golpe por reprodução: planeje os pais e o acesso à creche.');return '<p class="plan-viability">'+flags.map(esc).join(' ')+'</p>';}
 function coverage(){const state=getProgress(),g=ctx.editorial?.gyms[Math.min(state.badges,7)];if(!g)return '';let attack=Object.keys(typePT).find(t=>typePT[t]===g.type);if(state.badges===0)attack={Snivy:'Fire',Tepig:'Water',Oshawott:'Grass'}[state.starter];return `<p>Referência: ${esc(g.leader)} · ${esc(attack?typePT[attack]:g.type)}. Esta leitura usa apenas os tipos; habilidades, golpes de cobertura e níveis podem mudar o combate.</p>${state.team.map(name=>{const v=state.teamPlan[name]||{},current=v.current||name,types=data.pokemon[current]?.types||[],factor=attack?typeMultiplier(ctx.combat.chart,attack,types):1,moves=[...new Set((v.moves||[]).filter(m=>ctx.combat.moves[m]?.damage&&!['Hidden Power','Weather Ball','Natural Gift','Judgment','Techno Blast'].includes(m)).map(m=>ctx.combat.moves[m].type))];return `<article class="plan-overview-row"><b>${esc(current)}</b><p>${esc(types.map(t=>typePT[t]).join(' / '))}${attack?' · recebe '+factor+'× de '+typePT[attack]:''}</p><small>Tipos ofensivos planejados: ${esc(moves.map(t=>typePT[t]).join(', ')||'ainda não definidos')}. Os golpes são metas; não significa que seu integrante atual já os tenha.</small></article>`;}).join('')}<p>${esc(g.advice)}</p>`;}
 function timeline(name){const v=getProgress().teamPlan[name]||{},a=acquisition(name),route=a.rows[0];return `<div class="plan-timeline">${viability(name)}${route?`<div class="plan-step"><small>01 · OBTER</small><b>${esc(route.species)}</b><p>${esc(step(route))}${route.lock?' · '+esc(route.lock):''}</p>${location(route.area[0])}${route.special?`<p>${esc(route.special[2])}</p>`:`<small>${esc(ctx.methodInfo(route.table.method,route.area[0])[0])} · ${route.rate}% · Nv. ${esc(route.level)}</small>`}</div>`:`<div class="plan-step"><b>Obtenção a conferir</b><p>${esc(ctx.acquisition[name]||'Sem encontro direto cadastrado; verifique trocas, eventos e a família evolutiva.')}</p></div>`}${a.chain.length>1?`<div class="plan-step"><small>02 · EVOLUIR</small>${data.evolutions.filter(e=>a.chain.includes(e.fromSpecies)&&a.chain.includes(e.toSpecies)).map(e=>`<p><b>${esc(e.fromSpecies)} → ${esc(e.toSpecies)}</b><br>${esc(e.condition)}</p>${e.item?itemHTML(e.item):''}`).join('')}</div>`:''}${v.moves?.length?`<div class="plan-step"><small>03 · GOLPES DESEJADOS</small>${v.moves.map(m=>moveHTML(name,m,v)).join('')}</div>`:''}${v.item?`<div class="plan-step"><small>04 · ITEM DESEJADO</small>${itemHTML(v.item)}</div>`:''}<p class="plan-footnote">Insígnias estimam acesso aos locais. Nível de evolução, história, estação, troca e itens continuam sendo requisitos separados.</p></div>`;}
 function member(name,index){const v=getProgress().teamPlan[name]||{moves:[]},opened=name===openName;return `<details class="plan-member" data-member="${esc(name)}" ${opened?'open':''}><summary><span class="plan-slot">${String(index+1).padStart(2,'0')}</span><span><b>${esc(tab==='current'?(v.current||'Integrante ainda não informado'):name)}</b><small>${tab==='current'?'Meta: '+esc(name):esc(v.role||'Defina seu plano')}${v.moves?.length?' · '+v.moves.length+' golpe'+(v.moves.length>1?'s':''):''}</small></span><span class="plan-chevron" aria-hidden="true">+</span></summary><div class="plan-member-body">${opened?editor(name,v):''}</div></details>`;}
 function editor(name,v){const legal=[...moveOptions(data,name).keys()].sort();return `<div class="plan-member-heading"><h2>${esc(name)}</h2><button type="button" data-plan-remove="${esc(name)}">Tirar do plano</button></div><p class="plan-footnote">Todos os campos são opcionais. Seu plano não marca capturas nem altera sua equipe no jogo.</p><label>Quem ocupa esta vaga agora?<select data-plan-field="current">${options(species,v.current,'Não informado')}</select></label><label>Nível atual<input data-plan-field="level" type="number" inputmode="numeric" min="1" max="100" value="${v.level||''}" placeholder="Opcional"></label><label>Função na equipe<input data-plan-field="role" type="text" maxlength="80" value="${esc(v.role)}" placeholder="Ex.: capturador, atacante, suporte"></label><fieldset><legend>Golpes desejados · escolha só os que quiser</legend>${[0,1,2,3].map(i=>`<label>Golpe ${i+1}<select data-plan-move="${i}">${options(legal,v.moves?.[i],'Deixar vazio')}</select></label>`).join('')}</fieldset><label>Item desejado<select data-plan-field="item">${options(itemNames,v.item,'Sem item planejado')}</select></label><small>Catálogo de itens do guia. Confira no jogo se o item escolhido pode ser equipado; aqui também há consumíveis e itens de evolução.</small><p class="plan-save" role="status">${esc(ctx.saveStatus?.()||'Alterações salvas automaticamente neste aparelho.')}</p><details class="plan-nested" open><summary>Como montar este integrante</summary>${timeline(name)}</details>`;}
 function overview(){const p=getProgress();return p.team.map(n=>{const v=p.teamPlan[n]||{},a=acquisition(n),r=a.rows[0];return `<article class="plan-overview-row"><b>${esc(n)}</b><p>${esc(r?step(r)+' · '+r.species+' em '+r.area[1]:ctx.acquisition[n]||'Obtenção a conferir')}</p>${r?.lock?`<small>${esc(r.lock)}</small>`:''}${v.current?`<small>Agora: ${esc(v.current)}${v.level?' · Nv. '+v.level:''}</small>`:''}${v.moves?.length?`<small>Golpes: ${esc(v.moves.join(' · '))}</small>`:''}${v.item?`<small>Item: ${esc(v.item)}</small>`:''}<button type="button" data-plan-edit="${esc(n)}">Abrir plano</button></article>`;}).join('')||'<p>Adicione o primeiro integrante para começar.</p>';}
 function resources(){const names=new Set();for(const name of getProgress().team){const v=getProgress().teamPlan[name]||{};if(v.item)names.add(v.item);const chain=family(data,name);data.evolutions.filter(e=>chain.includes(e.fromSpecies)&&chain.includes(e.toSpecies)&&e.item).forEach(e=>names.add(e.item));for(const move of v.moves||[])for(const rows of Object.values(items))for(const r of rows)if(r.move===move||r.name===move)names.add(r.name);}return [...names].map(n=>`<details class="plan-nested"><summary>${esc(n)}</summary>${itemHTML(n)}${(()=>{const row=Object.values(items).flat().find(r=>r.name===n&&r.move);if(!row)return '';const compatible=getProgress().team.filter(mon=>(moveOptions(data,mon).get(row.move)||[]).some(r=>r.method===4));return '<p>Integrantes do plano que aprendem este TM/HM (inclui pré-evoluções): '+esc(compatible.join(', ')||'nenhum cadastrado')+'. Compare com a função que você escolheu para cada um.</p>';})()}</details>`).join('')||'<p>Escolha golpes e itens para reunir os recursos do plano.</p>';}
 function alternatives(name){const desired=data.pokemon[name]?.types||[];return species.filter(n=>n!==name&&ctx.available(n)&&data.pokemon[n]?.types.some(t=>desired.includes(t))).slice(0,5);}
 function refresh(){if(!host||host.hidden)return;const p=getProgress();if(!p.team.includes(openName))openName='';host.innerHTML=`<header class="plan-intro"><span class="section-index">EQUIPE / PLANEJAR</span><h1>Seu time, do início à Liga.</h1><p>Escolha quem você quer usar. Abra um integrante para planejar golpes, item e como obtê-lo.</p><span class="plan-count">${p.team.length} de 6 integrantes</span></header><div class="plan-switch" role="group" aria-label="Visão da equipe">${[['ideal','Ideal'],['current','Atual'],['timeline','Linha do tempo']].map(([id,label])=>`<button type="button" data-plan-tab="${id}" aria-pressed="${tab===id}">${label}</button>`).join('')}</div>${tab==='timeline'?`<div class="plan-overview">${overview()}</div>`:`<div class="plan-members">${p.team.map(member).join('')}</div><form id="plan-add-form" class="plan-add"><label for="plan-species">Novo integrante</label><div><select id="plan-species">${options(species.filter(n=>ctx.isSpeciesVisible(n)&&!p.team.includes(n)),'','Escolha um Pokémon')}</select><button type="submit" ${p.team.length>=6?'disabled':''}>Adicionar</button></div><p id="plan-message" role="status"></p></form>`}<details class="plan-nested"><summary>Recursos para montar a equipe</summary>${resources()}</details><details class="plan-nested"><summary>Tipos da equipe e próximo ginásio</summary>${coverage()}</details><details class="plan-nested"><summary>Opções temporárias e treinamento</summary><p>As opções abaixo compartilham pelo menos um tipo com sua meta e têm obtenção compatível com o progresso informado. Compare golpes e função antes de escolher.</p>${p.team.map(n=>`<article class="plan-overview-row"><b>${esc(n)}</b><p>${esc(alternatives(n).join(', ')||'Sem alternativa compatível cadastrada agora.')}</p></article>`).join('')}<p>Para ganhar experiência, procure Audino na grama que se mexe em um local acessível. Compare o nível da sua equipe com o do próximo ginásio em Ferramentas. O guia não calcula dano nem garante vitória por nível.</p></details>`;}
 function patch(name,changes){const p=getProgress();update({teamPlan:{...p.teamPlan,[name]:{...(p.teamPlan[name]||{moves:[]}),...changes}}});}
 function mount(element){host=element;host.addEventListener('submit',e=>{if(e.target.id!=='plan-add-form')return;e.preventDefault();const n=host.querySelector('#plan-species').value,p=getProgress();if(!n){host.querySelector('#plan-message').textContent='Escolha um Pokémon.';return;}if(p.team.length>=6||p.team.includes(n))return;openName=n;update({team:[...p.team,n]});refresh();});host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.planTab){tab=b.dataset.planTab;refresh();}if(b.dataset.planArea)ctx.openArea(b.dataset.planArea);if(b.dataset.planRemove){const name=b.dataset.planRemove;update({team:getProgress().team.filter(n=>n!==name)});refresh();}if(b.dataset.planEdit){tab='ideal';openName=b.dataset.planEdit;refresh();}});host.addEventListener('toggle',e=>{const member=e.target;if(!member.matches('.plan-member')||!member.open||member.dataset.member===openName)return;openName=member.dataset.member;host.querySelectorAll('.plan-member').forEach(d=>{if(d!==member){d.open=false;d.querySelector('.plan-member-body').innerHTML='';}});member.querySelector('.plan-member-body').innerHTML=editor(openName,getProgress().teamPlan[openName]||{moves:[]});},true);host.addEventListener('change',e=>{const el=e.target,member=el.closest('[data-member]');if(!member)return;const n=member.dataset.member;if(el.dataset.planField){const k=el.dataset.planField;patch(n,{[k]:k==='level'?Number(el.value):el.value});}else if(el.hasAttribute('data-plan-move')){patch(n,{moves:[...member.querySelectorAll('[data-plan-move]')].map(s=>s.value).filter(Boolean)});}refresh();});refresh();}
 return {mount,refresh,timeline,overview,itemNames,moveOptions:name=>moveOptions(data,name),alternatives};
}
root.createTeamPlanner=createTeamPlanner;root.normalizeTeamPlan=normalizeTeamPlan;
if(typeof module!=='undefined')module.exports={family,moveOptions,evolutionWarning,normalizeTeamPlan,typeMultiplier,createTeamPlanner};
})(typeof window!=='undefined'?window:globalThis);
