const {JSDOM}=require('jsdom'),fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('node:assert/strict');
const root=path.join(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
async function boot(page,saved){const dom=new JSDOM(read(page),{url:'https://example.test/'+page+'?game=black',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,d=w.document;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollTo=()=>{};w.matchMedia=()=>({matches:true});const key=page==='index.html'?'unova-black-field-guide-v2':'unova-black2-complete-1.12-v1';w.localStorage.setItem(key,JSON.stringify(saved));for(const script of d.querySelectorAll('script[src]')){const src=script.getAttribute('src');const r=vm.runInContext(read(src),dom.getInternalVMContext());if(src==='app.js'||src==='black2-app.js')await r;}return {dom,w,d,key};}
(async()=>{
 let {dom,w,d,key}=await boot('index.html',{badges:5,starter:'Snivy',season:'Summer',caught:['Chandelure'],collectedItems:['TM61'],notes:{ct:'continuar'},surf:false});
 const click=s=>{const e=d.querySelector(s);assert.ok(e,s);e.click();},change=(id,value)=>{const e=d.getElementById(id);e.value=value;e.dispatchEvent(new w.Event('change'));},has=n=>!!d.querySelector('#dex-list [data-caught="'+n+'"]');
 click('[data-view="dex"]');assert.equal(d.querySelectorAll('.dex-entry').length,156);click('[data-order="journey"]');assert.equal(has('Basculin'),false);assert.equal(has('Petilil'),false);assert.equal(has('Goldeen'),false);assert.equal(has('Hydreigon'),false);assert.equal(has('Chandelure'),true);assert.match(d.querySelector('#dex-list [data-caught="Chandelure"]').closest('section').textContent,/Já obtidos/);
 click('#surf-toggle');assert.equal(has('Basculin'),true);assert.equal(d.querySelector('#dex-list [data-caught="Basculin"]').closest('section').querySelector('h3').textContent,'Rota 1');click('#surf-toggle');assert.equal(has('Basculin'),false);
 click('#dex-list [data-caught="Cottonee"]');assert.equal(has('Petilil'),true);click('#dex-list [data-caught="Cottonee"]');assert.equal(has('Petilil'),false);
 // Badge/season and fishing changes refresh the visible view immediately.
 change('badge-count','0');assert.equal(has('Litwick'),false);change('badge-count','5');assert.equal(has('Litwick'),true);
 click('[data-scope="field"]');change('badge-count','8');click('#rod-toggle');assert.equal(has('Goldeen'),false);click('#league-toggle');assert.equal(has('Goldeen'),true);click('#rod-toggle');assert.equal(has('Goldeen'),false);
 click('[data-scope="unova"]');click('[data-order="dex"]');assert.equal(d.querySelectorAll('.dex-entry').length,156);assert.equal(has('Hydreigon'),true);
 const save=JSON.parse(w.localStorage.getItem(key));assert.ok(save.caught.includes('Chandelure'));assert.ok(save.collectedItems.includes('TM61'));assert.equal(save.notes.ct,'continuar');dom.window.close();
 ({dom,w,d}=await boot('black2.html',{badges:0,caught:[],starter:''}));d.querySelector('[data-view="dex"]').click();d.querySelector('[data-order="journey"]').click();assert.equal(d.querySelector('#dex-list [data-caught="Snivy"]'),null);assert.equal(d.querySelector('#dex-list [data-caught="Tepig"]'),null);const start=d.querySelector('#starter-select');start.value='Snivy';start.dispatchEvent(new w.Event('change'));assert.ok(d.querySelector('#dex-list [data-caught="Snivy"]'));assert.equal(d.querySelector('#dex-list [data-caught="Tepig"]'),null);dom.window.close();
 console.log('Live acquisition order: Surf, story, fishing, offering, obtained records, complete dex, hack starter passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
