const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs'),vm=require('vm'),path=require('path');
const read=n=>fs.readFileSync(path.join(__dirname,'..',n),'utf8');const c={};vm.createContext(c);vm.runInContext(read('pokemon-guide-data.js')+read('adventure-data.js')+read('walkthrough.js')+read('items.js')+';this.data=pokemonGuideData;this.editorial=adventureData;this.chapters=walkthroughChapters;this.items=itemTables;',c);
const {createAdventureGuide}=require('../adventure.js');
const areas=[['r1','Rota 1'],['ct','Celestial Tower'],['ope','Opelucid City']];const table={method:'Standard Surfing',sections:['Main'],seasons:[],pokemon:[['Basculin',100,'10 - 20']]};
function guide(patch={}){const progress={badges:0,league:false,surf:false,caught:[],collectedItems:[],team:[],tasks:[],notes:{},...patch};const ctx={areas,encounters:{r1:[table],ct:[{...table,method:'Walking',sections:['2F'],pokemon:[['Litwick',100,'26 - 29']]}]},specials:{},stage:{r1:0,ct:5,ope:7},editorial:c.editorial,data:c.data,chapters:c.chapters,allSpecies:['Litwick','Basculin','Swoobat','Gigalith'],items:c.items,getProgress:()=>progress,spoilerLocked:a=>progress.spoilerFree&&(a[0]==='ct'||a[0]==='ope'),availableNames:a=>a[0]==='r1'&&progress.surf?['Basculin']:[],lockReason:(a,t)=>t.method.includes('Surf')&&!progress.surf?'Você precisa de Surf':'',specialLock:()=>'',methodInfo:m=>[m,''],sectionLabel:s=>s,seasonLabel:s=>s,acquisition:{},itemMatches:(r,q)=>r.name.toLowerCase().includes(q.toLowerCase())};return createAdventureGuide(ctx);}
test('BW data uses generation V types and friendship, and excludes future evolutions',()=>{assert.equal(c.data.versionGroup,'black-white');assert.equal(Object.keys(c.data.pokemon).length,649);assert.equal(c.data.pokemon.Clefairy.types.join(','),'Normal');assert.ok(c.data.evolutions.find(e=>e.toSpecies==='Swoobat').condition.includes('220'));assert.ok(!c.data.pokemon.Sylveon);assert.equal(c.data.evolutions.find(e=>e.toSpecies==='Gigalith').fromSpecies,'Boldore');assert.equal(c.data.evolutions.filter(e=>e.fromSpecies==='Wurmple').length,2);});
test('evolution chains and move searches have BW level and machine methods',()=>{const g=guide();assert.equal(g.ancestors('Chandelure').join(','),'Litwick,Lampent,Chandelure');assert.ok(g.evolution('Litwick').some(e=>e.condition.includes('41')));assert.ok(c.data.pokemon.Pikachu.moves.some(([m,method])=>m==='Thunderbolt'&&method===4));assert.ok(!c.data.pokemon.Pikachu.moves.some(([m])=>m==='Nuzzle'));});
test('return suggestions depend on resources and exclude already obtained species',()=>{assert.equal(guide().returns().length,0);assert.equal(guide({surf:true}).returns()[0].names[0],'Basculin');assert.ok(guide({surf:true,caught:['Basculin']}).returns().every(r=>r.names.length===0));});
test('diagnostic separates wrong location from conditions and filters future locations',()=>{assert.match(guide().diagnose('Litwick','r1'),/Não há encontro desta espécie cadastrado neste local/);assert.match(guide().diagnose('Litwick'),/Celestial Tower/);assert.doesNotMatch(guide({spoilerFree:true}).diagnose('Litwick'),/Celestial Tower/);assert.match(guide().diagnose('Basculin'),/Você precisa de Surf/);});
test('remaining items respect collection marks and machine unavailability',()=>{const g=guide({collectedItems:['TM61']});assert.ok(!g.remaining('ct').items.some(r=>r.id==='TM61'));assert.equal(g.remaining('ct').items.length,4);});
test('task, team, note and spoiler fields migrate without losing captures',()=>{const n={normalizeTeamPlan:require('../team-plan.js').normalizeTeamPlan,pokemonGuideData:c.data,itemTables:c.items,itemGuide:require('../item-guide.js').createItemGuide(c.items),allSpecies:['Litwick','Basculin'],byId:new Map(areas.map(a=>[a[0],a]))};vm.createContext(n);const app=read('app.js');vm.runInContext(app.slice(app.indexOf('  const defaults='),app.indexOf('  let progress=normalizeProgress'))+';this.normalize=normalizeProgress;',n);const p=n.normalize({caught:['Litwick'],team:['Litwick','Litwick','invalid'],tasks:['chapter-0-0','invalid'],notes:{r1:'<b>lembrete</b>',invalid:'x'},spoilerFree:true});assert.equal(p.caught.join(','),'Litwick');assert.equal(p.team.join(','),'Litwick');assert.equal(p.tasks.join(','),'chapter-0-0');assert.equal(p.notes.r1,'<b>lembrete</b>');assert.ok(!p.notes.invalid);assert.equal(p.spoilerFree,true);});
test('services and calendar point to physical map locations and BW gyms have correct level references',()=>{const coords=require('../map-data.js').coordinates;for(const r of [...c.editorial.services,...c.editorial.agenda])assert.ok(coords[r.area],r.area);assert.equal(c.editorial.gyms.map(g=>g.ace).join(','),'14,20,23,27,31,35,39,43');});
