const {test}=require('node:test');const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../cloud-sync.js'),'utf8');
function setup(config={url:'https://example.supabase.co',key:'sb_publishable_test'}){
 const controls=new Map();const element={innerHTML:'',querySelector(sel){if(!controls.has(sel))controls.set(sel,{value:sel.includes('email')?'player@example.com':sel.includes('code')?'123456':'',hidden:false,textContent:'',checkValidity:()=>true});return controls.get(sel);}};
 let server=null,local={caught:['Patrat'],badges:1},calls=0;const records=new Map(),timers=new Set();
 const window={UNOVA_CLOUD:config,navigator:{onLine:true},localStorage:{getItem:k=>records.get(k)||null,setItem:(k,v)=>records.set(k,v),removeItem:k=>records.delete(k)},addEventListener(){}};
 const context={window,atob,setTimeout:(fn,n)=>{const t=setTimeout(fn,n);timers.add(t);return t;},clearTimeout,JSON,Date};vm.createContext(context);vm.runInContext(source,context);
 const request=async(url,opts)=>{calls++;let result;if(url.includes('/verify'))result={access_token:'test',refresh_token:'refresh',expires_in:3600,user:{id:'user-a'}};else if(url.includes('/journeys?'))result=server?[server]:[];else if(url.includes('/save_journey')){const body=JSON.parse(opts.body);if(body.p_expected!==(server?.revision||0))result={ok:false};else{server={data:body.p_data,revision:(server?.revision||0)+1};result={ok:true,revision:server.revision};}}else result={};return {ok:true,json:async()=>result};};
 const sync=window.createCloudSync({element,getProgress:()=>local,setProgress:p=>{local=p;},request});return {sync,element,setLocal:p=>{local=p},getLocal:()=>local,getServer:()=>server,setServer:p=>{server=p},getCalls:()=>calls,close:()=>timers.forEach(clearTimeout)};
}
test('unconfigured or secret-key cloud integration does not transmit progress',()=>{for(const config of [{url:'',key:''},{url:'https://example.supabase.co',key:'sb_secret_bad'}]){const h=setup(config);assert.equal(h.sync.enabled,false);assert.equal(h.getCalls(),0);h.close();}});
test('cloud CAS rejects concurrent writes and leaves the local journey intact',async()=>{const h=setup();await h.element.querySelector('[data-cloud-verify]').onclick();assert.equal(h.getServer().revision,1);h.setServer({data:{caught:['Audino'],badges:3},revision:2});h.setLocal({caught:['Patrat','Litwick'],badges:5});h.sync.schedule();await h.sync.flush();assert.equal(h.getServer().data.caught[0],'Audino');assert.equal(h.getLocal().caught[1],'Litwick');assert.equal(h.element.querySelector('[data-cloud-conflict]').hidden,false);await h.element.querySelector('[data-cloud-use-remote]').onclick();assert.equal(h.getLocal().caught[0],'Audino');h.close();});
test('SQL restricts every row to its owner and writes compare the revision',()=>{const sql=fs.readFileSync(path.join(__dirname,'../supabase/schema.sql'),'utf8');assert.match(sql,/enable row level security/);assert.match(sql,/security invoker/);assert.match(sql,/where user_id=auth.uid\(\) and revision=p_expected/);assert.match(sql,/revoke all on public.journeys from anon/);});
