const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../pokemon-guide-data.js'),'utf8')+';this.data=pokemonGuideData;',c);
const {moveOptions,evolutionWarning,normalizeTeamPlan}=require('../team-plan.js');
test('desired final forms include legal pre-evolution moves but no future-version moves',()=>{const m=moveOptions(c.data,'Breloom');assert.ok(m.get('Spore').some(r=>r.species==='Shroomish'));assert.ok(!moveOptions(c.data,'Pikachu').has('Nuzzle'));});
test('zero to four optional moves and blank items survive normalization',()=>{const n=normalizeTeamPlan({Litwick:{moves:[],role:'capturador'},Chandelure:{moves:['Shadow Ball','Shadow Ball','invented'],item:'Dusk Stone',current:'Litwick',level:30}},['Litwick','Chandelure'],c.data,['Dusk Stone']);assert.deepEqual(n.Litwick.moves,[]);assert.equal(n.Litwick.item,'');assert.deepEqual(n.Chandelure.moves,['Shadow Ball']);assert.equal(n.Chandelure.current,'Litwick');});
test('exclusive pre-evolution moves warn, while a final-form machine prevents a false lockout',()=>{assert.match(evolutionWarning(c.data,'Breloom','Spore'),/antes de evoluir/);assert.equal(evolutionWarning(c.data,'Chandelure','Shadow Ball'),'');});
test('imported plans reject invalid species, levels, items and oversized roles',()=>{const p=normalizeTeamPlan({Litwick:{current:'invalid',level:900,item:'invented',role:'x'.repeat(200),moves:['Ember']},invalid:{moves:[]}},['Litwick'],c.data,[]);assert.equal(p.Litwick.current,'');assert.equal(p.Litwick.level,0);assert.equal(p.Litwick.item,'');assert.equal(p.Litwick.role.length,80);assert.ok(!p.invalid);});
test('battle roster is Black final N and Ghetsis, with correct first League levels',()=>{const b={window:{}};vm.createContext(b);vm.runInContext(fs.readFileSync(path.join(__dirname,'../battle-guide.js'),'utf8')+';this.data=battleGuideData;',b);const n=b.data.battles.find(x=>x.name==='N · confronto final em Black');assert.equal(n.team[0][0],'Zekrom');assert.equal(n.team[0][1],52);const g=b.data.battles.find(x=>x.name.startsWith('Ghetsis'));assert.equal(g.team.find(r=>r[0]==='Hydreigon')[1],54);for(const row of b.data.battles.filter(x=>x.name.includes('primeira Liga')))assert.equal(row.team.map(r=>r[1]).join(','),'48,48,48,50');assert.equal(b.data.legends.find(x=>x.name==='Tornadus').stage,8);});

test('Gen V Steel resists Ghost and Dark, and dual types multiply',()=>{const d={};vm.createContext(d);vm.runInContext(fs.readFileSync(path.join(__dirname,'../combat-data.js'),'utf8')+';this.data=combatData;',d);const {typeMultiplier}=require('../team-plan.js');assert.equal(typeMultiplier(d.data.chart,'Ghost',['Steel']),.5);assert.equal(typeMultiplier(d.data.chart,'Dark',['Steel']),.5);assert.equal(typeMultiplier(d.data.chart,'Fire',['Bug','Steel']),4);assert.equal(typeMultiplier(d.data.chart,'Electric',['Ground']),0);});
