"""Generate edition-specific manifests with exact asset hashes and raw download sizes."""
from pathlib import Path
import hashlib,json,re
root=Path(__file__).resolve().parent.parent
entries={'pokemon-black':'index.html','pokemon-black2-complete-unova-1.12':'black2.html','pokemon-platinum':'platinum.html'}
backgrounds={'pokemon-black':'unova-base.svg','pokemon-black2-complete-unova-1.12':'black2-base.svg','pokemon-platinum':'packages/platinum/map.svg'}
common=['manifest.webmanifest','apple-touch-icon.png']+[str(p.relative_to(root)) for p in sorted((root/'icons').glob('*'))]
packs={}
for edition,page in entries.items():
 html=(root/page).read_text()
 files=set(common+[page,backgrounds[edition]])
 files.update(re.findall(r'<script src="([^"]+)"',html))
 files.update(re.findall(r'<link rel="stylesheet" href="([^"]+)"',html))
 assets={}
 for file in sorted(files):
  assert not file.startswith('/') and '..' not in Path(file).parts
  data=(root/file).read_bytes();assets['/'+file]=hashlib.sha256(data).hexdigest()
 packs[edition]={'entry':'/'+page,'bytes':sum((root/f).stat().st_size for f in files),'assets':assets}
template=(root/'scripts/service-worker-template.js').read_text()
manifest=json.dumps(packs,ensure_ascii=False,separators=(',',':'))
build=hashlib.sha256((manifest+template).encode()).hexdigest()[:12]
(root/'sw.js').write_text('/* Generated by scripts/build-service-worker.py; edit the template, then regenerate. */\nconst BUILD='+json.dumps(build)+',PACKS='+manifest+';\n'+template)
print('unova-guide-pack-'+build, {id:len(p['assets']) for id,p in packs.items()})
