"""Build only Platinum's initial slice from pinned PokeAPI CSVs and local editorial data.
Usage: python scripts/build-platinum-data.py /path/to/csv (or --download)
"""
import csv, hashlib, json, sys, urllib.request, tempfile
from pathlib import Path
from collections import defaultdict
root=Path(__file__).resolve().parent.parent
package=root/'packages/platinum'
lock=json.loads((package/'sources.json').read_text())
if sys.argv[1:] == ['--download']:
 folder=Path(tempfile.mkdtemp(prefix='platinum-csv-'))
 for name in lock['csv']:
  url=f"https://raw.githubusercontent.com/PokeAPI/pokeapi/{lock['revision']}/data/v2/csv/{name}.csv"
  (folder/(name+'.csv')).write_bytes(urllib.request.urlopen(url,timeout=60).read())
else:
 folder=Path(sys.argv[1])
def rows(name):
 p=folder/(name+'.csv')
 if hashlib.sha256(p.read_bytes()).hexdigest()!=lock['csv'][name]:raise ValueError('Source checksum mismatch: '+name)
 return list(csv.DictReader(p.open(encoding='utf-8')))
versions={r['id']:r for r in rows('versions')}
assert versions['14']['identifier']=='platinum' and versions['14']['version_group_id']=='9'
assert any(r['id']=='9' and r['generation_id']=='4' for r in rows('version_groups'))
assert any(r['id']=='6' and r['identifier']=='extended-sinnoh' for r in rows('pokedexes'))
names={r['pokemon_species_id']:r['name'] for r in rows('pokemon_species_names') if r['local_language_id']=='9'}
pokemon={r['id']:r['species_id'] for r in rows('pokemon')}
dex=sorted([[int(r['pokedex_number']),int(r['species_id']),names[r['species_id']]] for r in rows('pokemon_dex_numbers') if r['pokedex_id']=='6'])
assert len(dex)==210 # Platinum expands Sinnoh's original 151 to 210.
slots={r['id']:r for r in rows('encounter_slots')}
conditions={r['id']:r for r in rows('encounter_condition_values')}
condition_map=defaultdict(list)
for r in rows('encounter_condition_value_map'):condition_map[r['encounter_id']].append(conditions[r['encounter_condition_value_id']])
editorial=json.loads((package/'editorial.json').read_text())
area_map={str(s['sourceArea']):(a['id'],s) for a in editorial['areas'] for s in a.get('sections',[])}
methods={'1':'walk','2':'old-rod','3':'good-rod','4':'super-rod','5':'surf'}
groups=defaultdict(list); omitted=0
for row in rows('encounters'):
 if row['version_id']!='14' or row['location_area_id'] not in area_map:continue
 slot=slots[row['encounter_slot_id']]
 # Gifts are editorial, not random rolls. No radar/swarm/dual-slot table is mixed into ordinary walking.
 if slot['encounter_method_id'] not in methods:continue
 cs=condition_map[row['id']]
 if any(c['encounter_condition_id']!='2' and c['is_default']!='1' for c in cs):omitted+=1;continue
 times=[c['identifier'] for c in cs if c['encounter_condition_id']=='2'] or ['time-morning','time-day','time-night']
 area,section=area_map[row['location_area_id']];method=methods[slot['encounter_method_id']]
 for time in times if method=='walk' else ['any']:
  groups[(area,section['name'],method,time,section.get('rockSmash',False))].append((row,slot))
tables=defaultdict(list)
for (area,section,method,time,rock),entries in groups.items():
 mons={};seen=set()
 for row,slot in entries:
  assert slot['id'] not in seen, ('Duplicate active encounter slot',area,section,method,time,slot['id'])
  seen.add(slot['id']);name=names[pokemon[row['pokemon_id']]]
  v=mons.setdefault(name,[0,int(row['min_level']),int(row['max_level'])]);v[0]+=int(slot['rarity']);v[1]=min(v[1],int(row['min_level']));v[2]=max(v[2],int(row['max_level']))
 assert sum(v[0] for v in mons.values())==100,(area,method,time,mons)
 tables[area].append({'method':method,'time':time,'sections':[section],'seasons':[], 'requires':{'rockSmash':rock},'source':lock['encountersUrl'],'pokemon':[[n,v[0],str(v[1]) if v[1]==v[2] else f'{v[1]} - {v[2]}'] for n,v in mons.items()]})
areas=[[a['id'],a['name'],a['type'],a['x'],a['y']] for a in editorial['areas']]
data={'version':14,'generation':4,'pokedexId':6,'dex':dex,'areas':areas,'places':{a['id']:a for a in editorial['areas']},'paths':editorial['paths'],'chapters':editorial['chapters'],'items':editorial['items'],'encounters':tables,'audit':{'revision':lock['revision'],'omittedConditionalRows':omitted}}
(package/'data.js').write_text('/* Generated by scripts/build-platinum-data.py; edit editorial.json and pinned sources, then regenerate. */\nwindow.PlatinumData='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';\n')
print(len(areas),'places,',len(dex),'dex entries,',sum(map(len,tables.values())),'ordinary encounter tables; conditional rows excluded:',omitted)
